-- Creación de la tabla Requerimiento
CREATE TABLE Requerimiento (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255),
    VMO VARCHAR(255),
    solicitante VARCHAR(255),
    asignacion VARCHAR(255),
    requerimiento VARCHAR(255),
    cv VARCHAR(255),
    telefono VARCHAR(255),
    correo VARCHAR(255),
    dni VARCHAR(255),
    nombre VARCHAR(255),
    trabajo VARCHAR(255),
    disponibilidad VARCHAR(255),
    antecedentes VARCHAR(255),
    trabajoHits VARCHAR(255),
    familiaresHits VARCHAR(255),
    trabajoVinculado VARCHAR(255),
    pasoTrabajoVinculado VARCHAR(255),
    fuente VARCHAR(255),
    fechaNacimiento VARCHAR(255),
    todosTelefonos VARCHAR(255),
    puesto VARCHAR(255),
    empleador_ VARCHAR(255),
    institucion_ VARCHAR(255),
    carreras VARCHAR(255),
    grados VARCHAR(255),
    salario VARCHAR(255),
    espectativa VARCHAR(255),
    beneficio VARCHAR(255),
    puestoHits VARCHAR(255),
    pregunta1 VARCHAR(255),
    pregunta2 VARCHAR(255),
    pregunta3 VARCHAR(255),
    pregunta4 VARCHAR(255),
    nombre_puesto VARCHAR(255),
    adjunto1 VARCHAR(255),
    adjunto2 VARCHAR(255),
    adjunto3 VARCHAR(255),
    adjunto4 VARCHAR(255),
    antecedentesA VARCHAR(255),
    antecedentesB VARCHAR(255),
    antecedentePolicial VARCHAR(255),
    antecedentePenal VARCHAR(255),
    antecedenteJudicial VARCHAR(255),
    certiAdulto VARCHAR(255),
    multiTest VARCHAR(255),
    informePsicologico VARCHAR(255),
    fichaDatos VARCHAR(255),
    fichaMedica VARCHAR(255),
    fichaRequerimiento VARCHAR(255),
    fichaAprobacion VARCHAR(255),
    otrosAdjuntos VARCHAR(255),
    adjuntoBase VARCHAR(255),
    fechaSolicitud VARCHAR(255),
    tecnologia VARCHAR(255),
    seniority VARCHAR(255),
    cliente VARCHAR(255),
    prioridad VARCHAR(255),
    motivo VARCHAR(255),
    OBS_CANCELADOS VARCHAR(255),
    proyectos VARCHAR(255),
    n_cv_enviados VARCHAR(255),
    fec_cancelacion VARCHAR(255),
    canditado_contratado VARCHAR(255),
    fec_envio_cv VARCHAR(255),
    fec_envio_canditato VARCHAR(255),
    fec_aceptacion VARCHAR(255),
    fec_ing_contratado VARCHAR(255),
    fec_ing_planilla VARCHAR(255),
    fuente_reclutamiento VARCHAR(255),
    cod_sap VARCHAR(255),
    base VARCHAR(255),
    createdAtAudit TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Creación de la tabla Usuario
CREATE TABLE Usuario (
    nombreUsuario VARCHAR(255) PRIMARY KEY,
    contraseña VARCHAR(255),
    perfil VARCHAR(255),
    email VARCHAR(255),
    status VARCHAR(255)
);

